### ISSUE TITLE
Virtual rides from Zwift do not appear in the list of activities 

### ISSUE THREAD

**Issue by Konstantin-Levin** [Gerben321/bike-care-tracker#35]
**Describe the bug**
Virtual rides, in my case from Zwift, do not appear in the main list of activites. I can confim the distance travelled/time spent on these virtual rides is still being recorded on the component page for the 'bike' I have assigned as my indoor trainer.

I was using TrainerRoad app in 2022 and these _are_ being shown correctly in my history.

Is this by design perhaps? Even though the kilometres are virtual they are still causing wear on my chain, cassette, chainrings etc!

Many thanks

**Desktop (please complete the following information):**
 Firefox on macOS

**Smartphone (please complete the following information):**
 Safari on iOS

**Comment by Gerben321** [comment]
Ah I didn't take account for virtual rides! This is a recent change where I filter out anything that's not a bike ride. It seems Strava places virtual rides in a different category, so I have to add that to the whitelist.

The idea is that I wanted to keep the activities list clean without the daily walks or other stuff you do like swimming, because it's not relevant for this app. 

But don't worry, like you said it's still calculating the distance etc. I'll check this soon.

**Comment by Gerben321** [comment]
I'm now deploying the new version and you should see the activities. Let me know in case you can't see them.

**Comment by Konstantin-Levin** [comment]
Looks perfect! Thanks for updating so quickly 🙂
