### ISSUE TITLE
Component mounting/unmounting action

### ISSUE THREAD

**Issue by OleksiyRudenko** [Gerben321/bike-care-tracker#65]
**Is your feature request related to a problem? Please describe.**
Currently, if I want to swap components on the same bike I need to edit components' usage time periods.

**Describe the solution you'd like**
I want a button for every component, that says Unmount for a mounted component and Mount for a non-mounted component and clicking the button would do the relevant and required magic on BE.
Ideally, it wouldn't be possible to have 2+ components of the same type (assuming right and left pedals, from and rear wheels are different types) be mounted at the same time, i.e. only one component of a type can be Unmounted, and any components are not mountable if at least 1 component of the same type is mounted. Altho when no component of a specific type is mounted yet, any of other components would be mountable.

Please allow NFC/QR for the action (same NFC/QR to unmount if the component is mounted, and mount if it is unmounted).

**Describe alternatives you've considered**
Editing components' usage time periods and making sure they do not overlap.

**Additional context**
n/a

**Comment by Gerben321** [comment]
Yeah this is a good idea! How about that we place it here? Add a button to the 'Component actions' list add a button that says 'mount' or 'unmount' depending on the current status?
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/4b3dce14-1b04-4d3c-944a-bfb6e21ed356)

Should clicking that button directly mount or unmount it? Because maybe a little popup would be good where you get a date time selector (with the current date and time), in case you're a day late with mounting or unmounting. That way you can still quickly mount or unmount a component, but also get to enter the date in case it's different from now.

The NFC/QR code will have no input and directly execute. Do you want a toggle, or do you want two separate entries from mount and unmount?

Edit: Now that I think about it, maybe also add an icon when a component is added to your bike, but doesn't have a 'install period' yet. 🤔

**Comment by OleksiyRudenko** [comment]
Having dialog is good. Provides flexibility and double check.

I vote for toggle. No need to double the number of NFCs. The same NFC may also serve well as a swap action trigger for #66

**Comment by Konstantin-Levin** [comment]
Related to mounted and unmounted, is it worth considering having 'retired' as a separate, third state at the bottom of the list of components page?

Having a list of retired components can be useful, as the user can reference back and compare the longevity of things. Separating retired and unmounted is also helpful as parts wear out and sometimes break and will never be used again. These are often replaced with brand new versions of the same component. 

The obviously example being the chain:
- _How many kilometres did I get out of my last chain?_
- _Why didn't my current chain last as long?_
- _Maybe it was because I changed lubricant_
etc.

This is something the Strava's _My Gear_ page has and would be nice to see in Bike Care.

**Comment by Konstantin-Levin** [comment]
Also related is a useful feature I've seen elsewhere, which is a button to 'replace' a component when registering a service. This would carry out multiple actions for the user:
1. Adds the component and its total km/hrs to the list of retired components 
2. Creates a new component with the same name, details and service schedules with its usage reset to 0km/0hrs

Quite a common occurrence with wear parts like chains, cassettes, brake pads, bearings etc.

**Comment by Gerben321** [comment]
> Related to mounted and unmounted, is it worth considering having 'retired' as a separate, third state at the bottom of the list of components page?
> 
> Having a list of retired components can be useful, as the user can reference back and compare the longevity of things. Separating retired and unmounted is also helpful as parts wear out and sometimes break and will never be used again. These are often replaced with brand new versions of the same component. 
> 
> The obviously example being the chain:
> - _How many kilometres did I get out of my last chain?_
> - _Why didn't my current chain last as long?_
> - _Maybe it was because I changed lubricant_
> etc.
> 
> This is something the Strava's _My Gear_ page has and would be nice to see in Bike Care.

My idea is to rename the current 'active' toggle on a component to retired. This doesn't really do anything but we can separate components in that way.

**Comment by Gerben321** [comment]
> Also related is a useful feature I've seen elsewhere, which is a button to 'replace' a component when registering a service. This would carry out multiple actions for the user:
> 1. Adds the component and its total km/hrs to the list of retired components 
> 2. Creates a new component with the same name, details and service schedules with its usage reset to 0km/0hrs
> 
> Quite a common occurrence with wear parts like chains, cassettes, brake pads, bearings etc.

I get what you mean. But maybe a better place for this is at the 'to be retired' component right? Clicking that button will show  popup with confirmation. And explanation what it will do. It will check the option 'retired' for the old component. and indeed copy all service schedules (not logs)  to a new component with the same name and type.

I'm only thinking, should we directly be able to set the new installation date? Or just click replace and you will be directed to the new part where you can enter the mounted date later?

**Comment by Konstantin-Levin** [comment]
>I'm only thinking, should we directly be able to set the new installation date? Or just click replace and you will be directed to the new part where you can enter the mounted date later?

Hmm, both would be fine I think, but I'd go for the second option as I can imagine circumstances where the user might not know when a replacement was being installed (maybe waiting for a replacement part in the post?)

**Comment by Gerben321** [comment]
While working on #64 I will also work on this one since I now know whether a component is mounted or not in my frontend code.

The idea is to show this for unmounted components:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/f8471323-f1aa-4f90-8b62-96eb740af83e)
And this for mounted components:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/318113df-01e2-4180-a9f6-d22d32adbbfd)

Clicking the button will then open a dialog to enter the date of when it was mounted or unmounted.

**Comment by Gerben321** [comment]
I've worked on the mounting dialog today. This is how it will look like:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/002bb802-284e-40d6-a21e-66bbb0b75fc3)
If the date is not correct (if it overlaps) you will get an error. And when it's successfully mounted you will see that directly in the list as well.

Next up is the unmounting, but I think that will go a lot quicker because I've done the biggest work for this.

**Comment by Gerben321** [comment]
Also made the unmounting working now. I think it works great. I will do some cleaning up on the code and then hope to deploy it somewhere today or later this week.

Edit: Let me know what you think! It's deployed now.

**Comment by Konstantin-Levin** [comment]
Had a quick play around and looks to be working well so far! 👏
I'll be doing a big swap over of summer/winter components on my gravel bike within the next few weeks so I'll be able to give it a real world test soon.
