### ISSUE TITLE
Sync equipment (bikes and components) with Strava

### ISSUE THREAD

**Issue by OleksiyRudenko** [Gerben321/bike-care-tracker#67]
**Is your feature request related to a problem? Please describe.**
As a user I may have some components already defined in Strava. I may want to import those with all their props.
I would use BikeCare to manage components but would be willing to have the components' data be uploaded to Strava.

**Describe the solution you'd like**
Sync action for components.

**Describe alternatives you've considered**
none

**Additional context**
n/a

**Comment by OleksiyRudenko** [comment]
For clarity, not critical IMO.

**Comment by Gerben321** [comment]
This is not possible as far as I know. The Strava API only allows to update/create/retrieve what they call 'gear'. That's shoes for walkers, and bikes for bikers. A bike in our case only consists of the basic fields like name, brand, etc. There is no component data inside that I can update/create/retrieve. I believe that's also a text somewhere in Bike Care, that you shouldn't create components and expect them to be synced, because that is not possible. In saw that multiple person requested this in the Strava community/forum, but no answer yet. Their API is a low priority it seems.
