### ISSUE TITLE
Incomplete url in email notification

### ISSUE THREAD

**Issue by OleksiyRudenko** [Gerben321/bike-care-tracker#70]
**Describe the bug**
Overdue service email notification offers incomplete and unclickable url to the service.

**To Reproduce**
1. Receive email notification

**Expected behavior**
Link to service is followable

**Screenshots**
![Screenshot_2024-03-28-06-58-55-67_e307a3f9df9f380ebaf106e1dc980bb6.jpg](https://github.com/Gerben321/bike-care-tracker/assets/8686631/3f76decb-2b22-4730-bb85-004c64deef0f)

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
 - Device: one+ 8t
 - OS: Android 14
 - Browser: Gmail native client
 - Version: latest

**Additional context**
N/A

**Comment by Gerben321** [comment]
The emails are indeed not complete right now. The link is relative instead of absolute. I wanted to make them better in general anyway, I've made an issue about it here: https://github.com/Gerben321/bike-care-tracker/issues/50

**Comment by Gerben321** [comment]
I'm working on improving the e-mails in general. They will just display the data instead of the ugly list.

For the overdue schedules I will use a different template which will display a list of overdue schedule(s) with a link to click.

In the future I would like to give it a basic layout with some styling, but for now it's a step in the right direction, I think. Let me know if it's good for now.
